package jasmin;

import java.util.Hashtable;
import org.apache.tools.ant.taskdefs.Definer;
import soot.jimple.Jimple;
/* loaded from: gencallgraphv3.jar:jasmin-3.0.3-SNAPSHOT.jar:jasmin/InsnInfo.class */
class InsnInfo {
    static Hashtable infoTable = new Hashtable();
    public String name;
    public int opcode;
    public String args;

    InsnInfo() {
    }

    public static InsnInfo get(String name) {
        return (InsnInfo) infoTable.get(name);
    }

    public static boolean contains(String name) {
        return infoTable.get(name) != null;
    }

    private static void addInfo(String name, int opcode, String args) {
        InsnInfo info = new InsnInfo();
        info.name = name;
        info.opcode = opcode;
        info.args = args;
        infoTable.put(name, info);
    }

    static {
        addInfo("aaload", 50, "");
        addInfo("aastore", 83, "");
        addInfo("aconst_null", 1, "");
        addInfo("aload", 25, "i");
        addInfo("aload_0", 42, "");
        addInfo("aload_1", 43, "");
        addInfo("aload_2", 44, "");
        addInfo("aload_3", 45, "");
        addInfo("anewarray", 189, "class");
        addInfo("areturn", 176, "");
        addInfo("arraylength", 190, "");
        addInfo("astore", 58, "i");
        addInfo("astore_0", 75, "");
        addInfo("astore_1", 76, "");
        addInfo("astore_2", 77, "");
        addInfo("astore_3", 78, "");
        addInfo("athrow", 191, "");
        addInfo("baload", 51, "");
        addInfo("bastore", 84, "");
        addInfo("bipush", 16, "i");
        addInfo(Jimple.BREAKPOINT, 202, "");
        addInfo("caload", 52, "");
        addInfo("castore", 85, "");
        addInfo("checkcast", 192, "class");
        addInfo("d2f", 144, "");
        addInfo("d2i", 142, "");
        addInfo("d2l", 143, "");
        addInfo("dadd", 99, "");
        addInfo("daload", 49, "");
        addInfo("dastore", 82, "");
        addInfo("dcmpg", 152, "");
        addInfo("dcmpl", 151, "");
        addInfo("dconst_0", 14, "");
        addInfo("dconst_1", 15, "");
        addInfo("ddiv", 111, "");
        addInfo("dload", 24, "i");
        addInfo("dload_0", 38, "");
        addInfo("dload_1", 39, "");
        addInfo("dload_2", 40, "");
        addInfo("dload_3", 41, "");
        addInfo("dmul", 107, "");
        addInfo("dneg", 119, "");
        addInfo("drem", 115, "");
        addInfo("dreturn", 175, "");
        addInfo("dstore", 57, "i");
        addInfo("dstore_0", 71, "");
        addInfo("dstore_1", 72, "");
        addInfo("dstore_2", 73, "");
        addInfo("dstore_3", 74, "");
        addInfo("dsub", 103, "");
        addInfo("dup", 89, "");
        addInfo("dup2", 92, "");
        addInfo("dup2_x1", 93, "");
        addInfo("dup2_x2", 94, "");
        addInfo("dup_x1", 90, "");
        addInfo("dup_x2", 91, "");
        addInfo("f2d", 141, "");
        addInfo("f2i", 139, "");
        addInfo("f2l", 140, "");
        addInfo("fadd", 98, "");
        addInfo("faload", 48, "");
        addInfo("fastore", 81, "");
        addInfo("fcmpg", 150, "");
        addInfo("fcmpl", 149, "");
        addInfo("fconst_0", 11, "");
        addInfo("fconst_1", 12, "");
        addInfo("fconst_2", 13, "");
        addInfo("fdiv", 110, "");
        addInfo("fload", 23, "i");
        addInfo("fload_0", 34, "");
        addInfo("fload_1", 35, "");
        addInfo("fload_2", 36, "");
        addInfo("fload_3", 37, "");
        addInfo("fmul", 106, "");
        addInfo("fneg", 118, "");
        addInfo("frem", 114, "");
        addInfo("freturn", 174, "");
        addInfo("fstore", 56, "i");
        addInfo("fstore_0", 67, "");
        addInfo("fstore_1", 68, "");
        addInfo("fstore_2", 69, "");
        addInfo("fstore_3", 70, "");
        addInfo("fsub", 102, "");
        addInfo("getfield", 180, "field");
        addInfo("getstatic", 178, "field");
        addInfo(Jimple.GOTO, 167, "label");
        addInfo("goto_w", 200, "label");
        addInfo("i2d", 135, "");
        addInfo("i2f", 134, "");
        addInfo("i2l", 133, "");
        addInfo("iadd", 96, "");
        addInfo("iaload", 46, "");
        addInfo("iand", 126, "");
        addInfo("iastore", 79, "");
        addInfo("iconst_0", 3, "");
        addInfo("iconst_1", 4, "");
        addInfo("iconst_2", 5, "");
        addInfo("iconst_3", 6, "");
        addInfo("iconst_4", 7, "");
        addInfo("iconst_5", 8, "");
        addInfo("iconst_m1", 2, "");
        addInfo("idiv", 108, "");
        addInfo("if_acmpeq", 165, "label");
        addInfo("if_acmpne", 166, "label");
        addInfo("if_icmpeq", 159, "label");
        addInfo("if_icmpge", 162, "label");
        addInfo("if_icmpgt", 163, "label");
        addInfo("if_icmple", 164, "label");
        addInfo("if_icmplt", 161, "label");
        addInfo("if_icmpne", 160, "label");
        addInfo("ifeq", 153, "label");
        addInfo("ifge", 156, "label");
        addInfo("ifgt", 157, "label");
        addInfo("ifle", 158, "label");
        addInfo("iflt", 155, "label");
        addInfo("ifne", 154, "label");
        addInfo("ifnonnull", 199, "label");
        addInfo("ifnull", 198, "label");
        addInfo("iinc", 132, "ii");
        addInfo("iload", 21, "i");
        addInfo("iload_0", 26, "");
        addInfo("iload_1", 27, "");
        addInfo("iload_2", 28, "");
        addInfo("iload_3", 29, "");
        addInfo("imul", 104, "");
        addInfo("ineg", 116, "");
        addInfo(Jimple.INSTANCEOF, 193, "class");
        addInfo("int2byte", 145, "");
        addInfo("int2char", 146, "");
        addInfo("int2short", 147, "");
        addInfo("i2b", 145, "");
        addInfo("i2c", 146, "");
        addInfo("i2s", 147, "");
        addInfo("invokeinterface", 185, "interface");
        addInfo("invokenonvirtual", 183, "method");
        addInfo("invokespecial", 183, "method");
        addInfo("invokestatic", 184, "method");
        addInfo("invokevirtual", 182, "method");
        addInfo("invokedynamic", 186, "invokedynamic");
        addInfo("ior", 128, "");
        addInfo("irem", 112, "");
        addInfo("ireturn", 172, "");
        addInfo("ishl", 120, "");
        addInfo("ishr", 122, "");
        addInfo("istore", 54, "i");
        addInfo("istore_0", 59, "");
        addInfo("istore_1", 60, "");
        addInfo("istore_2", 61, "");
        addInfo("istore_3", 62, "");
        addInfo("isub", 100, "");
        addInfo("iushr", 124, "");
        addInfo("ixor", 130, "");
        addInfo("jsr", 168, "label");
        addInfo("jsr_w", 168, "label");
        addInfo("l2d", 138, "");
        addInfo("l2f", 137, "");
        addInfo("l2i", 136, "");
        addInfo("ladd", 97, "");
        addInfo("laload", 47, "");
        addInfo("land", 127, "");
        addInfo("lastore", 80, "");
        addInfo("lcmp", 148, "");
        addInfo("lconst_0", 9, "");
        addInfo("lconst_1", 10, "");
        addInfo("ldc", 18, "constant");
        addInfo("ldc_w", 19, "constant");
        addInfo("ldc2_w", 20, "bigconstant");
        addInfo("ldiv", 109, "");
        addInfo("lload", 22, "i");
        addInfo("lload_0", 30, "");
        addInfo("lload_1", 31, "");
        addInfo("lload_2", 32, "");
        addInfo("lload_3", 33, "");
        addInfo("lmul", 105, "");
        addInfo("lneg", 117, "");
        addInfo(Jimple.LOOKUPSWITCH, 171, "switch");
        addInfo("lor", 129, "");
        addInfo("lrem", 113, "");
        addInfo("lreturn", 173, "");
        addInfo("lshl", 121, "");
        addInfo("lshr", 123, "");
        addInfo("lstore", 55, "i");
        addInfo("lstore_0", 63, "");
        addInfo("lstore_1", 64, "");
        addInfo("lstore_2", 65, "");
        addInfo("lstore_3", 66, "");
        addInfo("lsub", 101, "");
        addInfo("lushr", 125, "");
        addInfo("lxor", 131, "");
        addInfo("monitorenter", 194, "");
        addInfo("monitorexit", 195, "");
        addInfo("multianewarray", 197, "marray");
        addInfo("new", 187, "class");
        addInfo(Jimple.NEWARRAY, 188, "atype");
        addInfo(Jimple.NOP, 0, "");
        addInfo("pop", 87, "");
        addInfo("pop2", 88, "");
        addInfo("putfield", 181, "field");
        addInfo("putstatic", 179, "field");
        addInfo(Jimple.RET, 169, "i");
        addInfo("ret_w", 169, "i");
        addInfo("return", 177, "");
        addInfo("saload", 53, "");
        addInfo("sastore", 86, "");
        addInfo("sipush", 17, "i");
        addInfo("swap", 95, "");
        addInfo(Jimple.TABLESWITCH, 170, "switch");
        addInfo("wide", 196, Definer.OnError.POLICY_IGNORE);
    }
}
